### ISSUE TITLE
when will code to be released?

### ISSUE THREAD

**Issue by rkdckddnjs9** [ViewFormerOcc/ViewFormer-Occ#1]
Thanks for your excellent work!! and I wonder when you will release the code

**Comment by ViewFormerOcc** [comment]
> Thanks for your excellent work!! and I wonder when you will release the code

The code is ready. I've been busy with new work and life recently, so I haven't had the chance to take care of this. Apologies for the delay.

**Comment by rkdckddnjs9** [comment]
@ViewFormerOcc 
Thank you so much for getting back to me. I truly appreciate your time and effort, especially given how busy you’ve been with work and life.
