### ISSUE TITLE
dataset problem.

### ISSUE THREAD

**Issue by chenshi3** [ViewFormerOcc/ViewFormer-Occ#3]
Amazing work! But could you fix the bug in dataset download? The _url: https://huggingface.co/viewformer/ViewFormer-Occ_ can not be opened.

**Comment by ViewFormerOcc** [comment]
> Amazing work! But could you fix the bug in dataset download? The _url: https://huggingface.co/viewformer/ViewFormer-Occ_ can not be opened.

Perhaps you need a VPN to access Huggingface, or you can star this repository, and I will upload a cloud drive link :)
