### ISSUE TITLE
ViewFormer训练显存

### ISSUE THREAD

**Issue by lvchuandong** [ViewFormerOcc/ViewFormer-Occ#4]
很棒的工作呀~想问一下ViewFormer训练所使用的显存大约多少呢

**Comment by ViewFormerOcc** [comment]
> 很棒的工作呀~想问一下ViewFormer训练所使用的显存大约多少呢

有点记不清哪个模型是10G左右哪个是20G左右了。有机器你跑一下试试吧。

**Comment by lvchuandong** [comment]
> > 很棒的工作呀~想问一下ViewFormer训练所使用的显存大约多少呢
> 
> 有点记不清哪个模型是10G左右哪个是20G左右了。有机器你跑一下试试吧。

谢谢~
