### ISSUE TITLE
Unable to train on multi-GPU

### ISSUE THREAD

**Issue by DDEONSIK** [ViewFormerOcc/ViewFormer-Occ#5]
## Core Issue::
Single-GPU training works
Command: ```./occ_train.sh```

Unable to train on multi-GPU
My GPU: _GPU: NVIDIA GeForce RTX 4090 *2_

---

# Error Details:
Command: ```./tools/torchrun_occ_train.sh ./projects/configs/viewformer/viewformer_r50_704x256_seq_90e.py 2 --work-dir ./work_dirs/frist_train```
Training Status: Failed
Error: ```TypeError: cannot pickle 'dict_keys' object```
(Error occurs when using default multi-GPU training command)
<br/>

---

# Try

### 1. Code Modification
Modified: Set ```workers_per_gpu=0``` in ```ViewFormer-Occ/projects/configs/viewformer/viewformer_r50_704x256_seq_90e.py``` 
Command: ```./tools/torchrun_occ_train.sh ./projects/configs/viewformer/viewformer_r50_704x256_seq_90e.py 2 --work-dir ./work_dirs/frist_train```
Training Status: Success
Error: Performance bottleneck due to disabled multiprocessing<br/>

### 2. First Script Modification
Purpose: Attempt training with ```torch.distributed.launch```
Modified: Changed ```train.py``` to ```occ_train.py``` in ```ViewFormer-Occ/tools/dist_train.sh```
Command: ```./tools/dist_train.sh ./projects/configs/viewformer/viewformer_r50_704x256_seq_90e.py 2 --work-dir ./work_dirs/frist_train```
Training Status: Failed
Error:
```occ_train.py: error: unrecognized arguments: --local-rank=0```
```occ_train.py: error: unrecognized arguments: --local-rank=1```<br/>

### 3. Second Script Modification
Purpose: Attempt training with ```torch.distributed.launch```
Modified: Added ```--local_rank=$LOCAL_RANK```
Current Script:
```
#!/usr/bin/env bash

CONFIG=$1
GPUS=$2
PORT=${PORT:-29500}

PYTHONPATH="$(dirname $0)/..":$PYTHONPATH \
python -m torch.distributed.launch --nproc_per_node=$GPUS --master_port=$PORT \
    $(dirname "$0")/occ_train.py $CONFIG --launcher pytorch --local_rank=$LOCAL_RANK ${@:3}
```
    
Command: ```./tools/dist_train.sh ./projects/configs/viewformer/viewformer_r50_704x256_seq_90e.py 2 --work-dir ./work_dirs/frist_train```
Training Status: Failed
Error: ```occ_train.py: error: argument --local_rank: invalid int value: ''```<br/>

---

## Environment Configuration List
```
Ubuntu 20.04.6 LTS
Python 3.8.20
PyTorch: 2.0.1
CUDA version: 11.8

mmcv-full==1.6.0
mmdet==2.28.2
mmdet3d==1.0.0rc6
mmsegmentation==0.30.0
numpy==1.23.5
torch==2.0.1
torchvision==0.15.2
scipy==1.10.1

numba==0.53.0
llvmlite==0.36.0
pillow==10.4.0
yapf==0.32.0
platformdirs==4.3.6

```

Thank you for your work.

**Comment by ViewFormerOcc** [comment]
> TypeError: cannot pickle 'dict_keys' object

The issue is related [to this](https://discuss.pytorch.org/t/dataloader-multiprocessing-error-cant-pickle-odict-keys-objects-when-num-workers-0/43951/4)

One solution is as follows:
https://github.com/open-mmlab/mmdetection3d/issues/1364#issuecomment-1086782249

I would recommend another approach:
First, You can use the following command to find the installation path of the nuscenes library.

`python -c "import nuscenes; import os; print(os.path.dirname(nuscenes.__file__))"`

This command will output the installation path of the nuscenes library, and then you can find the **eval/detection/data_classes.py** file under that path.
You need to modify the line **self.class_names = self.class_range.keys()** to **self.class_names = list(self.class_range.keys())**, and then everything will work fine.

**Comment by DDEONSIK** [comment]
## Core Issue:
```zipfile.BadZipFile: Bad CRC-32 for file 'mask_lidar.npy'```
```zipfile.BadZipFile: Bad CRC-32 for file 'mask_camera.npy'```

<br/>
<br/>

---

### To solve the ```TypeError: cannot pickle ‘dict_keys’ object``` I did two things.

Modify the code in 
```./.conda/envs/view/lib/python3.8/site-packages/nuscenes/eval/detection/data_classes.py```

### 1. 
Proceed with modification in def __init__ in class DetectionConfig
```self.class_names = self.class_range.keys()``` 
-> 
```self.class_names = list(self.class_range.keys())```

### 2. 
class DetectionMetricDataList
```
    def set(self, detection_name: str, match_distance: float, data: DetectionMetricData):
        """ Sets the MetricData entry for a certain detection_name and match_distance. """
        self.md[(detection_name, match_distance)] = data
```
->
```
    def set(self, detection_name: str, match_distance: float, data: DetectionMetricData) -> None:
    """ Sets the MetricData entry for a certain detection_name and match_distance. """
    self.md[(detection_name, match_distance)] = data
```

Command:
nohup ./tools/torchrun_occ_train.sh ./projects/configs/viewformer/viewformer_r50_704x256_seq_90e.py 2 --work-dir ./work_dirs/frist_train > train_multi.log 2>&1

Training Status: Failed


### ```TypeError: cannot pickle 'dict_keys' object``` The training proceeds without an error, 
## but is aborted!

<br/>

Error:
-> Break at Iter 690
```zipfile.BadZipFile: Caught BadZipFile in DataLoader worker process 2.```
```zipfile.BadZipFile: Bad CRC-32 for file 'mask_camera.npy'```

This error also occurs in training on a single-GPU.
However, on a single-GPU, before modifying the code ```data_classes.py```, the error
```zipfile.BadZipFile: Caught BadZipFile in DataLoader worker process 2.```
```zipfile.BadZipFile: Bad CRC-32 for file 'mask_lidar.npy'```

<br/>

---


# Try 
### 1.
The file ```class DetectionMetricDataList``` in ```./nuscenes/eval/detection/data_classes.py``` is corrupted

reinstall and code modify
```pip uninstall nuscenes-devkit -y```
```pip install nuscenes-devkit==1.1.11```

```self.class_names = list(self.class_range.keys())```

```
    def set(self, detection_name: str, match_distance: float, data: DetectionMetricData) -> None:
    """ Sets the MetricData entry for a certain detection_name and match_distance. """
    self.md[(detection_name, match_distance)] = data
```

Retrain
-> Break at Iter 520
```./nuscenes/eval/detection/data_classes.py``` is well maintained

Error:
```zipfile.BadZipFile: Caught BadZipFile in DataLoader worker process 0```
```zipfile.BadZipFile: Bad CRC-32 for file 'mask_lidar.npy'```
CRC-32 Error: File Integrity Problem



### 2.
1. Estimate the problem with the dataset file ```depth_pano_seg_gt```
Uninstall and re-download

2. File permissions and integrity checks were also performed.

<br/>


## However, ```mask_camera.npy``` and ```mask_lidar.npy``` are not found.

Thank you for your work.

**Comment by ViewFormerOcc** [comment]
I haven't encountered a problem like yours, so I'm not very clear about your issue. The code in [this part](https://github.com/ViewFormerOcc/ViewFormer-Occ/blob/f38b57559c6bb9384f12b8b08019b39bc5e96401/projects/mmdet3d_plugin/datasets/pipelines/loading.py#L210) will load mask_camera/mask_lidar, which originates from [Occ3D](https://github.com/CVPR2023-3D-Occupancy-Prediction/CVPR2023-3D-Occupancy-Prediction/tree/main) You need to follow occ3D to prepare the dataset.
